before:
  hooks:
    - go mod download
builds:
  - id: doqd
    dir: cmd/daemon/
    binary: doqd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: doqd
    package_name: doqd
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Nate Sales
    homepage: https://natesales.net/
    maintainer: Nate Sales <nate@natesales.net>
    description: DNS over QUIC implementation in Go
    license: GNU GPL-3.0
    section: utils
    priority: extra
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - doqd
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -s -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/natesales/
